### ISSUE TITLE
Could not find the GDAL library

### ISSUE THREAD

**Issue by eracle** [bashu/django-airports#13]
Hi there!
I just tried installing the app into a brand new django 2 project and after having installed the app, both in pip and in setting.py, when typing python manage.py check, it gives me:

```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/eracle/git/byway/backend/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/eracle/git/byway/backend/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/home/eracle/git/byway/backend/.venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/eracle/git/byway/backend/.venv/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/eracle/git/byway/backend/.venv/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/eracle/git/byway/backend/.venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/eracle/git/byway/backend/.venv/lib/python3.6/site-packages/airports/models.py", line 3, in <module>
    from django.contrib.gis.db import models
  File "/home/eracle/git/byway/backend/.venv/lib/python3.6/site-packages/django/contrib/gis/db/models/__init__.py", line 3, in <module>
    import django.contrib.gis.db.models.functions  # NOQA
  File "/home/eracle/git/byway/backend/.venv/lib/python3.6/site-packages/django/contrib/gis/db/models/functions.py", line 3, in <module>
    from django.contrib.gis.db.models.fields import BaseSpatialField, GeometryField
  File "/home/eracle/git/byway/backend/.venv/lib/python3.6/site-packages/django/contrib/gis/db/models/fields.py", line 3, in <module>
    from django.contrib.gis import forms, gdal
  File "/home/eracle/git/byway/backend/.venv/lib/python3.6/site-packages/django/contrib/gis/forms/__init__.py", line 3, in <module>
    from .fields import (  # NOQA
  File "/home/eracle/git/byway/backend/.venv/lib/python3.6/site-packages/django/contrib/gis/forms/fields.py", line 2, in <module>
    from django.contrib.gis.geos import GEOSException, GEOSGeometry
  File "/home/eracle/git/byway/backend/.venv/lib/python3.6/site-packages/django/contrib/gis/geos/__init__.py", line 5, in <module>
    from .collections import (  # NOQA
  File "/home/eracle/git/byway/backend/.venv/lib/python3.6/site-packages/django/contrib/gis/geos/collections.py", line 9, in <module>
    from django.contrib.gis.geos.geometry import GEOSGeometry, LinearGeometryMixin
  File "/home/eracle/git/byway/backend/.venv/lib/python3.6/site-packages/django/contrib/gis/geos/geometry.py", line 8, in <module>
    from django.contrib.gis import gdal
  File "/home/eracle/git/byway/backend/.venv/lib/python3.6/site-packages/django/contrib/gis/gdal/__init__.py", line 28, in <module>
    from django.contrib.gis.gdal.datasource import DataSource
  File "/home/eracle/git/byway/backend/.venv/lib/python3.6/site-packages/django/contrib/gis/gdal/datasource.py", line 39, in <module>
    from django.contrib.gis.gdal.driver import Driver
  File "/home/eracle/git/byway/backend/.venv/lib/python3.6/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
  File "/home/eracle/git/byway/backend/.venv/lib/python3.6/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>
    from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
  File "/home/eracle/git/byway/backend/.venv/lib/python3.6/site-packages/django/contrib/gis/gdal/libgdal.py", line 43, in <module>
    % '", "'.join(lib_names)
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal2.2.0", "gdal2.1.0", "gdal2.0.0", "gdal1.11.0", "gdal1.10.0", "gdal1.9.0"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
```

That's my actual pip freeze configuration, I use Ubuntu 16.04 and python 3.6:
```
certifi==2018.1.18
chardet==3.0.4
Django==2.0.3
django-airports==0.1.4
django-cities==0.5.0.6
django-model-utils==3.1.1
idna==2.6
pytz==2018.3
requests==2.18.4
six==1.11.0
swapper==1.1.0
tqdm==4.19.6
urllib3==1.22
```

**Comment by eracle** [comment]
Ok I solved with:
`sudo apt-get install gdal-bin`

It should be noted in the readme.md file.
